### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by justincy** [rootsdev/scribeAPI#1]
Deploying to Heroku won't be as easy as I had hoped. Scribe uses [moped](https://github.com/mongoid/moped) for the mongodb driver and it only supports authentication with mongodb v2 while free databases on [mlab](https://mlab.com) (formerly mongolab) are v3 of mongo. I see three solutions:
1. Find a cloud mongo hosting service that supports mongo v2 for free (mlab supports it for paid plans but not free plans).
2. Update to a driver that supports v3 (I have no idea what this would entail)
3. Bite the bullet and pay for a small mongodb in the cloud

I noticed that the [tutorial for deploying to Heroku](https://github.com/zooniverse/scribeAPI/wiki/Setting-up-OAuth-%26-Deploying#register-db) recommends [Compose.io](https://github.com/zooniverse/scribeAPI/wiki/Setting-up-OAuth-%26-Deploying#register-db) instead of mlab (even though the env var name is the standard mongolab var). Perhaps this mongo v2 vs v3 issue is the reason why.

**Comment by benwbrum** [comment]
If it would help, I can contact the folks at UC Davis who also seem to be
working actively on scribe to see what their experience has been.

**Comment by tfmorris** [comment]
It seems like `moped` is a dead end and will never support MongoDB 3+ auth.

https://github.com/mongoid/moped/issues/387
https://www.mongodb.com/blog/post/announcing-ruby-driver-20-rewrite
https://docs.mongodb.org/ecosystem/tutorial/mongoid-upgrade/

Mongoid is currently at 5.1.2 and 5.0 was first released in Sept. 2015, so
it should be reasonably stable, although I don't know how big a task the
migration would be.

**Comment by justincy** [comment]
> If it would help, I can contact the folks at UC Davis who also seem to be
> working actively on scribe to see what their experience has been.

That could help. I might also open an issue on the main Scribe repo after researching more into the work required to migrate from moped to mongoid.

**Comment by justincy** [comment]
> It seems like `moped` is a dead end and will never support MongoDB 3+ auth.
> 
> mongoid/moped#387
> https://www.mongodb.com/blog/post/announcing-ruby-driver-20-rewrite
> https://docs.mongodb.org/ecosystem/tutorial/mongoid-upgrade/
> 
> Mongoid is currently at 5.1.2 and 5.0 was first released in Sept. 2015, so
> it should be reasonably stable, although I don't know how big a task the
> migration would be.

Thanks for those links. I'm going to attempt the migration to mongoid v5. It seems relatively easy and I should know pretty quickly whether I'm in over my head.

More migration tips: https://github.com/nodkz/migrating-from-mongoid-4-to-5

**Comment by tfmorris** [comment]
I think `moped` is a red herring. It's not used directly, so all we really need is `mongoid`.

I just updated to Mongoid 5 and am in the process of populating an Mlab DB using it. I should know shortly if it's functional, but I can push a PR while it's loading for others to look it.

Even if it passes a smoke test, it should be reviewed by Ben or someone else who knows Rails since I'm just faking it.

**Comment by tfmorris** [comment]
PR #2 has the changes. My test DB is still loading.
