### ISSUE TITLE
rake project:activate fails with undefined method dropIndexes

### ISSUE THREAD

**Issue by justincy** [rootsdev/scribeAPI#4]
```
NoMethodError: undefined method `dropIndexes' for #<Mongo::Collection:0x00000002eebc48>
/home/ubuntu/workspace/lib/tasks/project.rake:348:in `block (2 levels) in <top (required)>'
/home/ubuntu/workspace/lib/tasks/project.rake:112:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => project:create_indexes
```

This was likely caused by the upgrade to Mongoid v5

**Comment by tfmorris** [comment]
The original code was:

```
SubjectSet.collection.indexes.drop
```

which gave an error.  When I retested with the change, the error went away,
but it must have been on some one-time-only code path.

I _think_

```
SubjectSet.remove_indexes
```

will do a similar, albeit potentially less complete, job, but someone who
knows Rails/Rake should look at it.

**Comment by benwbrum** [comment]
That's what it looks like to me:
http://www.rubydoc.info/github/mongoid/mongoid/Mongoid%2FIndexable%2FClassMethods%3Aremove_indexes
​
